//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceTypesPrinters
    {
        public int invTypePrinterId { get; set; }
        public Nullable<int> printerId { get; set; }
        public Nullable<int> invoiceTypeId { get; set; }
        public Nullable<int> sizeId { get; set; }
        public string notes { get; set; }
        public int copyCount { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> createUserId { get; set; }
        public Nullable<int> updateUserId { get; set; }
    
        public virtual InvoiceTypes InvoiceTypes { get; set; }
        public virtual paperSize paperSize { get; set; }
        public virtual posPrinters posPrinters { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
