//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceTaxes
    {
        public int invoiceTaxId { get; set; }
        public Nullable<int> taxId { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> taxValue { get; set; }
        public string notes { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public string taxType { get; set; }
    
        public virtual invoices invoices { get; set; }
        public virtual taxes taxes { get; set; }
    }
}
