//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsMaterials
    {
        public int itemMatId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> materialId { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<int> unitId { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual items items { get; set; }
        public virtual items items1 { get; set; }
        public virtual units units { get; set; }
    }
}
