//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class serials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serials()
        {
            this.storeProperties = new HashSet<storeProperties>();
        }
    
        public int serialId { get; set; }
        public Nullable<int> itemsTransId { get; set; }
        public Nullable<int> itemUnitId { get; set; }
        public string serialNum { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> createUserId { get; set; }
        public Nullable<int> updateUserId { get; set; }
        public bool isSold { get; set; }
        public Nullable<int> branchId { get; set; }
    
        public virtual branches branches { get; set; }
        public virtual itemsTransfer itemsTransfer { get; set; }
        public virtual itemsUnits itemsUnits { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storeProperties> storeProperties { get; set; }
    }
}
