//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteContents
    {
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string contents { get; set; }
        public string lang { get; set; }
        public string category { get; set; }
    }
}
